---
- hosts: all
  become: true
  become_user: root
  become_method: sudo

  roles:
    - common
    - kubernetes-setup


###
# Playbook for Master
##
- import_playbook: master.yml

###
# Playbook for Worker
##
- import_playbook: worker.yml