---
# name: General package installation


- name: Add apt key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-{{ lsb_release_cs_result.stdout }} main
    state: present


- name: Install Kubernetes
  package:
    name="{{ item }}"
    state=present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Enable kubelet service
  service:
    name: kubelet
    enabled: yes

- name: Start kubelet service
  service:
    name: kubelet
    state: started

- name: Disable swap in kubelet configuration
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_EXTRA_ARGS=.*'
    line: 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"'
  register: kubelet_disable_swap

- name: Reload systemd daemon
  command: systemctl daemon-reload
  when: kubelet_disable_swap.changed

- name: Restart kubelet service after update configuration
  service:
    name: kubelet
    state: restarted
  when: kubelet_disable_swap.changed