---
# name: General package installation


- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "../vars/default.yml"

- name: Installation common package
  package:
    name="{{ item }}"
    state=present
  with_items: "{{common_install}}"

- name: Remove useless package
  package:
    name="{{ item }}"
    state=absent
  with_items:
    - common_remove

